name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Clean public
        working-directory: exampleSite
        run: rm -rf ./public/*

      - name: Build
        working-directory: exampleSite
        run: hugo --themesDir=../.. --minify --environment production -b https://ntk148v.github.io/shibui

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./exampleSite/public

      - name: Setup hugo cache
        uses: actions/cache@v4
        with:
          path: ./exampleSite/resources
          key: ${{ runner.os }}-hugo-${{ hashFiles('./exampleSite/resources') }}
          restore-keys: ${{ runner.os }}-hugo-
